- alias: roof_light_toggle
  trigger:
    - platform: state
      entity_id: sensor.c_bedroom_double_switch_action
      to: "single_left"
  action:
    - service: switch.toggle
      entity_id: switch.relay_wall_switch_bedroom
      
- alias: underbed_light_10
  trigger:
    - platform: state
      entity_id: sensor.c_bedroom_double_switch_action
      to: "single_right"
  action:
    - service: light.turn_on
      data:
        entity_id: light.magic_light
        brightness_pct: 10
    # - service: light.toggle
    #   entity_id: light.magic_light

- alias: underbed_light_100
  trigger:
    - platform: state
      entity_id: sensor.c_bedroom_double_switch_action
      to: "double_right"
  action:
    - service: light.turn_on
      data:
        entity_id: light.magic_light
        brightness_pct: 100
        
- alias: underbed_light_off
  trigger:
    - platform: state
      entity_id: sensor.c_bedroom_double_switch_action
      to: "hold_right"
  action:
    - service: light.turn_off
      data:
        entity_id: light.magic_light
      
- alias: light_off
  trigger:
    - platform: state
      entity_id: sensor.c_bedroom_double_switch_action
      to: "single_both"
  action:
    - service: switch.turn_off
      entity_id: switch.relay_wall_switch_bedroom
    - service: light.turn_off
      entity_id: light.magic_light  
      
- alias: underbed_light_toggle
  trigger:
    - platform: event
      event_type: esphome.wall_switch_action
      event_data:
        title: dbl_click
  action:
    - service: light.toggle
      data:
        entity_id: light.magic_light